import type { MaintenanceIssue, User, Vehicle } from "./types";

export const mockUsers: User[] = [
  { id: "u-mot-1", name: "Carlos Souza", role: "motorista" },
  { id: "u-mot-2", name: "João Pereira", role: "motorista" },
  { id: "u-mec-1", name: "Rafael Lima", role: "mecanico" },
  { id: "u-ges-1", name: "Ana Ribeiro", role: "gestor" },
];

const now = new Date();
const iso = (d: Date) => d.toISOString();
const daysAgo = (n: number) => iso(new Date(now.getTime() - n * 86400000));

export const mockVehicles: Vehicle[] = [
  {
    id: "v-bya",
    placa: "BYA2H92",
    frota: "F-101",
    marca: "Volvo",
    modelo: "FH 460 (antigo)",
    ano: 2015,
    tipo: "Cavalo mecânico",
    hodometro: 748_500,
    dataEntrada: "2015-03-12",
    status: "ok",
    ultimaRevisaoKm: 740_000,
    proximaRevisaoKm: 750_000,
  },
  {
    id: "v-awj",
    placa: "AWJ4B28",
    frota: "F-102",
    marca: "Scania",
    modelo: "R 500 (cabine estendida)",
    ano: 2018,
    tipo: "Cavalo mecânico",
    hodometro: 512_300,
    dataEntrada: "2018-07-01",
    status: "ok",
    ultimaRevisaoKm: 500_000,
    proximaRevisaoKm: 520_000,
  },
  {
    id: "v-atn66",
    placa: "ATN9E66",
    frota: "F-103",
    marca: "Mercedes-Benz",
    modelo: "Actros (chassi alongado)",
    ano: 2019,
    tipo: "Cavalo mecânico",
    implemento: "Tanque suplementar",
    hodometro: 389_100,
    dataEntrada: "2019-04-22",
    status: "ok",
    ultimaRevisaoKm: 380_000,
    proximaRevisaoKm: 390_000,
  },
  {
    id: "v-atn18",
    placa: "ATN9118",
    frota: "F-104",
    marca: "Iveco",
    modelo: "Stralis (histórico atenção)",
    ano: 2017,
    tipo: "Cavalo mecânico",
    hodometro: 619_800,
    dataEntrada: "2017-10-05",
    status: "atencao",
    ultimaRevisaoKm: 600_000,
    proximaRevisaoKm: 620_000,
  },
  {
    id: "v-hhk",
    placa: "HHK5I52",
    frota: "F-105",
    marca: "Volvo",
    modelo: "VM 270",
    ano: 2016,
    tipo: "Truck",
    hodometro: 428_600,
    dataEntrada: "2016-06-14",
    status: "ok",
    ultimaRevisaoKm: 420_000,
    proximaRevisaoKm: 430_000,
  },
  {
    id: "v-1",
    placa: "RXA-1B23",
    frota: "F-001",
    marca: "Volvo",
    modelo: "FH 540",
    ano: 2022,
    tipo: "Cavalo mecânico",
    implemento: "Bitrem graneleiro",
    hodometro: 184_320,
    dataEntrada: "2022-05-10",
    status: "ok",
    motoristaPrincipalId: "u-mot-1",
    ultimaRevisaoKm: 180_000,
    proximaRevisaoKm: 190_000,
  },
  {
    id: "v-2",
    placa: "RXB-4C56",
    frota: "F-002",
    marca: "Scania",
    modelo: "R 450",
    ano: 2021,
    tipo: "Cavalo mecânico",
    implemento: "Carreta baú",
    hodometro: 249_780,
    dataEntrada: "2021-08-20",
    status: "atencao",
    motoristaPrincipalId: "u-mot-2",
    ultimaRevisaoKm: 245_000,
    proximaRevisaoKm: 250_000,
  },
  {
    id: "v-3",
    placa: "RXC-7D89",
    frota: "F-003",
    marca: "Mercedes-Benz",
    modelo: "Actros 2651",
    ano: 2023,
    tipo: "Cavalo mecânico",
    hodometro: 92_150,
    dataEntrada: "2023-02-14",
    status: "nao_conforme",
    ultimaRevisaoKm: 90_000,
    proximaRevisaoKm: 100_000,
  },
  {
    id: "v-4",
    placa: "RXD-2E34",
    frota: "F-004",
    marca: "Volvo",
    modelo: "VM 270",
    ano: 2020,
    tipo: "Truck",
    hodometro: 312_400,
    dataEntrada: "2020-01-05",
    status: "ok",
    ultimaRevisaoKm: 310_000,
    proximaRevisaoKm: 320_000,
  },
  {
    id: "v-5",
    placa: "RXE-5F67",
    frota: "F-005",
    marca: "Iveco",
    modelo: "Tector 240E28",
    ano: 2019,
    tipo: "Truck",
    hodometro: 401_050,
    dataEntrada: "2019-06-18",
    status: "ok",
    ultimaRevisaoKm: 400_000,
    proximaRevisaoKm: 405_000,
  },
];

export const mockIssues: MaintenanceIssue[] = [
  {
    id: "i-1",
    vehicleId: "v-2",
    itemLabel: "Limpadores e esguicho",
    itemStatus: "atencao",
    descricao: "Palheta do motorista rasgando; substituir na próxima parada.",
    createdAt: daysAgo(2),
    hodometro: 249_500,
    abertoPor: "Carlos Souza",
    prazo: iso(new Date(now.getTime() + 5 * 86400000)),
    status: "aberta",
  },
  {
    id: "i-2",
    vehicleId: "v-3",
    itemLabel: "Freios e direção durante manobra",
    itemStatus: "nao_conforme",
    descricao: "Ruído metálico ao frear + puxada para a direita.",
    createdAt: daysAgo(1),
    hodometro: 92_100,
    abertoPor: "João Pereira",
    status: "em_analise",
    critica: true,
    mecanicoId: "u-mec-1",
  },
];
