/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppChecklistIdRouteImport } from './routes/app.checklist.$id'
import { Route as AppChecklistNovoRouteImport } from './routes/app.checklist.novo'
import { Route as AppPendenciasIndexRouteImport } from './routes/app.pendencias.index'
import { Route as AppPendenciasIdRouteImport } from './routes/app.pendencias.$id'
import { Route as AppVeiculosIndexRouteImport } from './routes/app.veiculos.index'
import { Route as AppVeiculosIdRouteImport } from './routes/app.veiculos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistIdRoute = AppChecklistIdRouteImport.update({
  id: '/checklist/$id',
  path: '/checklist/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistNovoRoute = AppChecklistNovoRouteImport.update({
  id: '/checklist/novo',
  path: '/checklist/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppPendenciasIndexRoute = AppPendenciasIndexRouteImport.update({
  id: '/pendencias/',
  path: '/pendencias/',
  getParentRoute: () => AppRoute,
} as any)
const AppPendenciasIdRoute = AppPendenciasIdRouteImport.update({
  id: '/pendencias/$id',
  path: '/pendencias/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosIndexRoute = AppVeiculosIndexRouteImport.update({
  id: '/veiculos/',
  path: '/veiculos/',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosIdRoute = AppVeiculosIdRouteImport.update({
  id: '/veiculos/$id',
  path: '/veiculos/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/checklist/$id': typeof AppChecklistIdRoute
  '/app/checklist/novo': typeof AppChecklistNovoRoute
  '/app/pendencias/$id': typeof AppPendenciasIdRoute
  '/app/veiculos/$id': typeof AppVeiculosIdRoute
  '/app/pendencias/': typeof AppPendenciasIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/app/checklist/$id': typeof AppChecklistIdRoute
  '/app/checklist/novo': typeof AppChecklistNovoRoute
  '/app/pendencias/$id': typeof AppPendenciasIdRoute
  '/app/veiculos/$id': typeof AppVeiculosIdRoute
  '/app/pendencias': typeof AppPendenciasIndexRoute
  '/app/veiculos': typeof AppVeiculosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/checklist/$id': typeof AppChecklistIdRoute
  '/app/checklist/novo': typeof AppChecklistNovoRoute
  '/app/pendencias/$id': typeof AppPendenciasIdRoute
  '/app/veiculos/$id': typeof AppVeiculosIdRoute
  '/app/pendencias/': typeof AppPendenciasIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/'
    | '/app/checklist/$id'
    | '/app/checklist/novo'
    | '/app/pendencias/$id'
    | '/app/veiculos/$id'
    | '/app/pendencias/'
    | '/app/veiculos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/checklist/$id'
    | '/app/checklist/novo'
    | '/app/pendencias/$id'
    | '/app/veiculos/$id'
    | '/app/pendencias'
    | '/app/veiculos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/'
    | '/app/checklist/$id'
    | '/app/checklist/novo'
    | '/app/pendencias/$id'
    | '/app/veiculos/$id'
    | '/app/pendencias/'
    | '/app/veiculos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checklist/$id': {
      id: '/app/checklist/$id'
      path: '/checklist/$id'
      fullPath: '/app/checklist/$id'
      preLoaderRoute: typeof AppChecklistIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checklist/novo': {
      id: '/app/checklist/novo'
      path: '/checklist/novo'
      fullPath: '/app/checklist/novo'
      preLoaderRoute: typeof AppChecklistNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pendencias/': {
      id: '/app/pendencias/'
      path: '/pendencias'
      fullPath: '/app/pendencias/'
      preLoaderRoute: typeof AppPendenciasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pendencias/$id': {
      id: '/app/pendencias/$id'
      path: '/pendencias/$id'
      fullPath: '/app/pendencias/$id'
      preLoaderRoute: typeof AppPendenciasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos/': {
      id: '/app/veiculos/'
      path: '/veiculos'
      fullPath: '/app/veiculos/'
      preLoaderRoute: typeof AppVeiculosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos/$id': {
      id: '/app/veiculos/$id'
      path: '/veiculos/$id'
      fullPath: '/app/veiculos/$id'
      preLoaderRoute: typeof AppVeiculosIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppChecklistIdRoute: typeof AppChecklistIdRoute
  AppChecklistNovoRoute: typeof AppChecklistNovoRoute
  AppPendenciasIdRoute: typeof AppPendenciasIdRoute
  AppVeiculosIdRoute: typeof AppVeiculosIdRoute
  AppPendenciasIndexRoute: typeof AppPendenciasIndexRoute
  AppVeiculosIndexRoute: typeof AppVeiculosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppChecklistIdRoute: AppChecklistIdRoute,
  AppChecklistNovoRoute: AppChecklistNovoRoute,
  AppPendenciasIdRoute: AppPendenciasIdRoute,
  AppVeiculosIdRoute: AppVeiculosIdRoute,
  AppPendenciasIndexRoute: AppPendenciasIndexRoute,
  AppVeiculosIndexRoute: AppVeiculosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
